name: Build OpenFL Project
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Haxe
      run: |
        sudo apt-get update
        sudo apt-get install haxe=4.2.1-1

    - name: Install Haxe Standard Library
      run: haxelib install hxcpp

    - name: Clean Haxe Cache
      run: haxelib clean

    - name: Install OpenFL
      run: haxelib install openfl
